# .github/workflows/main.yml

name: 自动构建并测试

on:
  push:
    branches: [ main ]  # 监听 main 分支的 push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 拉取代码
      uses: actions/checkout@v3

    - name: 设置 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 启动脚本
      run: |
        python app/app.py
