name: Flask 自动构建

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 拉取代码
      uses: actions/checkout@v3

    - name: 设置 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 运行 Flask 应用（测试启动用）
      run: |
        export FLASK_APP=app/app.py
        flask run --no-debugger --no-reload --port=5000
